CREATE VIEW [dbo].[FORNECEDORES_CLIENTE]
AS
SELECT FC.FORNECEDORID, FC.CLIENTEID, FC.ATIVO, FC.VISIVEL, DISTRIBUICAO, DATAVINCULO, NOME, OPERADORAID, CAPACIDADE FROM FORNECEDOR_CLIENTE FC 
JOIN FORNECEDOR F ON FC.FORNECEDORID=F.FORNECEDORID
JOIN FORNECEDOR_CAPACIDADE FCA ON FC.FORNECEDORID=FCA.FORNECEDORID