 CREATE VIEW [dbo].[GESTORESSMS]  
  AS  
  SELECT   
  G.NOME, G.CLIENTEID, GT.TELEFONE, GE.EMAIL, GC.CARTEIRAID, G.GESTORID, C.CARTEIRA, C.VISIVEL, C.LIMITE, C.DIAINICIO, C.DIASHIGIENIZACAO, C.PORCENTAGEMAVISO
  FROM GESTOR G   
  LEFT JOIN GESTOR_TELEFONES GT ON G.GESTORID=GT.GESTORID  
  LEFT JOIN GESTOR_EMAIL GE ON G.GESTORID=GE.GESTORID  
  LEFT JOIN GESTOR_CARTEIRAS GC ON G.GESTORID=GC.GESTORID  
  LEFT JOIN CARTEIRAS C ON GC.CARTEIRAID=C.CARTEIRAID AND G.CLIENTEID=C.CLIENTEID   
  GROUP BY G.NOME, G.CLIENTEID, GT.TELEFONE, GE.EMAIL, GC.CARTEIRAID, G.GESTORID, C.CARTEIRA, C.VISIVEL, C.LIMITE, C.DIAINICIO, C.DIASHIGIENIZACAO, C.PORCENTAGEMAVISO
  
  