CREATE TABLE [dbo].[CAMPANHAS_CONSOLIDADO]
(
	[CODIGO] INT NOT NULL PRIMARY KEY IDENTITY, 
    [CARTEIRAID] INT NOT NULL, 
    [ARQUIVOID] INT NULL, 
    [DATAENVIAR] SMALLDATETIME NOT NULL, 
    [USUARIOID] INT NULL, 
    [CLIENTEID] INT NOT NULL, 
	[EXCLUIDA] INT NOT NULL, 
    [ERRO] INT NOT NULL, 
    [SUSPENSA] INT NOT NULL, 
    [ENTREGUE] INT NOT NULL, 
    [EXPIRADA] INT NOT NULL, 
    [DATADIA] DATE NOT NULL, 
    [FORNECEDORID] INT NOT NULL, 
    [CANCELADA] INT NOT NULL, 
    [SPCAPITAL] INT NOT NULL, 
    [SPGRANDE] INT NOT NULL, 
    [DEMAISDDD] INT NOT NULL,
	[ENVIADA] INT NOT NULL,
	[ENVIADAS] AS ENTREGUE+EXPIRADA+EXCLUIDA+ENVIADA, 
	[NAOENVIADAS] AS ERRO+CANCELADA+SUSPENSA,
    [TIPOCAMPANHAID] TINYINT NULL, 
    [ATRASO] INT NOT NULL, 
    CONSTRAINT [FK_CAMPANHAS_CONSOLIDADOS_CARTEIRAS] FOREIGN KEY ([CARTEIRAID]) REFERENCES [dbo].[CARTEIRAS] ([CARTEIRAID]),
	CONSTRAINT [FK_CAMPANHAS_CONSOLIDADOS_ARQUIVOS] FOREIGN KEY ([ARQUIVOID]) REFERENCES [dbo].[CAMPANHAS_ARQUIVOS] ([ARQUIVOID]),
	CONSTRAINT [FK_CAMPANHAS_CONSOLIDADOS_USUARIO] FOREIGN KEY ([USUARIOID]) REFERENCES [dbo].[USUARIOS] ([USUARIOID])

)
