CREATE TABLE [dbo].[CAMPANHA_RETORNO] (
    [CODIGO]       INT           IDENTITY (1, 1) NOT NULL,
    [FORNECEDORID] INT           NOT NULL,
    [RETORNO]      VARCHAR (450) NOT NULL,
    [DATARETORNO]  DATETIME      NOT NULL,
    [DATA] DATETIME      DEFAULT (getdate()) NOT NULL,
    [CAMPANHAID]   BIGINT        NOT NULL,
    [CLASSIFICACAOID] INT NOT NULL, 
    [COMENTARIO]  VARCHAR(150) SPARSE NULL, 
    [SCORECLASSIFICACAO] DECIMAL(18, 6) NULL, 
    PRIMARY KEY CLUSTERED ([CODIGO] ASC), 
    CONSTRAINT [FK_CAMPANHA_RETORNO_RETORNO_CLASSIFICACAO] FOREIGN KEY (CLASSIFICACAOID) REFERENCES [RETORNO_CLASSIFICACAO](CODIGO), 
    CONSTRAINT [FK_CAMPANHA_RETORNO_ToTable] FOREIGN KEY (CLASSIFICACAOID) REFERENCES dbo.RETORNO_CLASSIFICACAO(CODIGO)
);

