CREATE TABLE [dbo].[CAMPANHAS_ARQUIVOS_FILESZIP]
(
	[CODIGO] INT NOT NULL PRIMARY KEY IDENTITY, 
    [ARQUIVO] VARCHAR(250) NOT NULL, 
    [ARQUIVOID] INT NOT NULL, 
    CONSTRAINT [FK_CAMPANHAS_ARQUIVOS_FILESZIP_CAMPANHAS_ARQUIVOS] FOREIGN KEY (ARQUIVOID) REFERENCES dbo.CAMPANHAS_ARQUIVOS(ARQUIVOID) ON DELETE CASCADE
)
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_CAMPANHAS_ARQUIVOS_FILESZIP_ARQUIVO] ON [dbo].[CAMPANHAS_ARQUIVOS_FILESZIP] (ARQUIVO ASC, ARQUIVOID ASC)
