CREATE TABLE [dbo].[CARTEIRAS] (
    [CARTEIRAID]       INT           IDENTITY (1, 1) NOT NULL,
    [CARTEIRA]         VARCHAR (150) NOT NULL,
    [IDCARTEIRA]       VARCHAR (50)  NULL,
    [USUARIOID]        INT           NULL,
    [CLIENTEID]        INT           NOT NULL,
    [DATA]             DATETIME      CONSTRAINT [DF__CARTEIRAS__DATAG__48CFD27E] DEFAULT (getdate()) NOT NULL,
    [LIMITE]           INT           NULL,
    [PERIODICIDADE]    SMALLINT      NULL,
    [DIAINICIO]        INT           NULL,
    [PORCENTAGEMAVISO] INT           NULL,
    [VISIVEL]          BIT           NOT NULL,
    [HIGIENIZA]        BIT           NOT NULL DEFAULT 0,
    [DIASHIGIENIZACAO] INT           NULL,
    [SEGMENTACAOID]    INT           NULL,
    [HORALIMITE] TIME NULL, 
    [BLOQUEIOENVIO] BIT NULL, 
    [ISEXCLUDED] BIT NOT NULL DEFAULT 0, 
    CONSTRAINT [PK__CARTEIRA__1ACAB244DB6FFCF3] PRIMARY KEY CLUSTERED ([CARTEIRAID] ASC)
);
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_CARTEIRA_carteira]
    ON [dbo].[CARTEIRAS]([CARTEIRA] ASC, CLIENTEID ASC);



