CREATE TABLE [dbo].[CELULARES_INVALIDOS_CONSOLIDADO]
(
	[CODIGO] INT NOT NULL PRIMARY KEY IDENTITY, 
    [TIPOINVALIDO] TINYINT NOT NULL, 
    [CLIENTEID] INT NOT NULL, 
    [USUARIOID] INT NULL, 
    [QUANTIDADE] INT NOT NULL, 
    [CARTEIRAID] INT NOT NULL, 
    [ARQUIVO]   VARCHAR(255) SPARSE NULL, 
    [DATADIA] DATE NOT NULL 
)
GO
