CREATE TABLE [dbo].[CELULAR_BLACKLIST] (
    [BLACKLISTID]       INT          IDENTITY (1, 1) NOT NULL,
    [CELULAR]      NUMERIC (11) NOT NULL,
    [DATA] DATETIME     NOT NULL,
    [CLIENTEID]    INT          NOT NULL,
    PRIMARY KEY CLUSTERED ([BLACKLISTID] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_CELULAR_BLACKLIST]
    ON [dbo].[CELULAR_BLACKLIST]([CELULAR] ASC, [CLIENTEID] ASC);

