CREATE TABLE [dbo].[CELULARES_INVALIDOS] (
    [CODIGO]       INT           IDENTITY (1, 1) NOT NULL,
    [CELULAR]      NUMERIC(15)  NOT NULL,
    [CLIENTEID]    INT           NOT NULL,
    [USUARIOID]    INT           NULL,
    [CARTEIRAID]   INT           NOT NULL,
    [ARQUIVO]      VARCHAR (250) SPARSE NULL,
    [DATAENVIAR]   DATETIME      NOT NULL,
    [TIPOINVALIDO] TINYINT           NOT NULL,
    [MENSAGEM]  VARCHAR(300)  NOT NULL, 
    [IDCLIENTE] VARCHAR(100) NULL, 
    PRIMARY KEY CLUSTERED ([CODIGO] ASC)
);
GO
CREATE NONCLUSTERED INDEX [CELULARES_INVALIDOS_Includes]
ON [dbo].[CELULARES_INVALIDOS] ([CLIENTEID],[CARTEIRAID],[ARQUIVO],[DATAENVIAR],TIPOINVALIDO)
INCLUDE ([CELULAR],[MENSAGEM],[IDCLIENTE])