CREATE TABLE [dbo].[CLIENTES] (
    [CLIENTEID]   INT           IDENTITY (1, 1) NOT NULL,
    [NOME]        VARCHAR (150) NOT NULL,
    [CNPJ]        VARCHAR (14)  NOT NULL,
    [ENDERECO]    VARCHAR (150) NULL,
    [NUMERO]      VARCHAR (10)  NULL,
    [COMPLEMENTO] VARCHAR (100) NULL,
    [BAIRRO]      VARCHAR (100) NULL,
    [CEP]         VARCHAR (8)   NULL,
    [CIDADE]      VARCHAR (150) NULL,
    [UF]          CHAR (2)      NULL,
    [DATA]        DATETIME      DEFAULT (getdate()) NOT NULL,
    [POSPAGO]		BIT NOT NULL DEFAULT 0, 
    [SALDO]			INT NOT NULL DEFAULT 0, 
    [ATIVO] BIT NOT NULL DEFAULT 0, 
    CONSTRAINT [PK__CLIENTES__566BBD8BD2FD1348] PRIMARY KEY CLUSTERED ([CLIENTEID] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_CLIENTES]
    ON [dbo].[CLIENTES]([CNPJ] ASC);

