CREATE TABLE [dbo].[CLIENTES_CONFIGURACAO]
(
	[CODIGO] INT NOT NULL PRIMARY KEY IDENTITY, 
    [CLIENTEID] INT NOT NULL, 
    [DISTRIBUICAOAUTOMATICA] BIT NOT NULL, 
    CONSTRAINT [FK_CLIENTES_CONFIGURACAO_CLIENTES] FOREIGN KEY (CLIENTEID) REFERENCES CLIENTES(CLIENTEID)
)
