CREATE TABLE [dbo].[CLIENTES_CONTATO] (
    [CODIGO]    INT IDENTITY (1, 1) NOT NULL,
    [CLIENTEID] INT NOT NULL,
    [TELEFONE] NUMERIC(14) NULL, 
    [EMAIL] VARCHAR(255) NULL, 
    [DESCRICAO] VARCHAR(50) NULL, 
    PRIMARY KEY CLUSTERED ([CODIGO] ASC),
    CONSTRAINT [FK_CLIENTES_CONTATO_CLIENTES] FOREIGN KEY ([CLIENTEID]) REFERENCES [dbo].[CLIENTES] ([CLIENTEID]) ON DELETE CASCADE ON UPDATE CASCADE,
);

GO

CREATE NONCLUSTERED INDEX [IX_EMAIL_CLIENTES_EMAIL_UNIQUE] ON dbo.CLIENTES_CONTATO(EMAIL) WHERE EMAIL IS NOT NULL