CREATE TABLE [dbo].[CONTATOS_FORNECEDOR]
(
	[CODIGO] INT NOT NULL PRIMARY KEY IDENTITY, 
    [EMAIL] VARCHAR(150) NULL, 
    [TELEFONE] DECIMAL(12) NULL, 
    [DESCRICAO] VARCHAR(150) NULL, 
    [FORNECEDORID] INT NOT NULL, 
    CONSTRAINT [FK_CONTATOS_FORNECEDOR_FORNECEDOR] FOREIGN KEY (FORNECEDORID) REFERENCES dbo.FORNECEDOR(FORNECEDORID)
)
