CREATE TABLE [dbo].[FORNECEDOR_SERVICO]
(
	[CODIGO] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[FORNECEDORID] INT NOT NULL CONSTRAINT FK_FORNECEDOR_SERVICO_fornecedorid FOREIGN KEY ([FORNECEDORID]) REFERENCES FORNECEDOR([FORNECEDORID]),
	[DATAINICIO] DATETIME NOT NULL,
	[DATAFIM] DATETIME NULL,
	[ISATIVO] BIT NOT NULL CONSTRAINT DF_FORNECEDOR_SERVICO_ISATIVO DEFAULT (0)
)
