CREATE TABLE [dbo].[FORNECEDOR] (
    [FORNECEDORID] INT           IDENTITY (1, 1) NOT NULL,
    [NOME]         VARCHAR (150) NOT NULL,
    [CPFCNPJ]      VARCHAR (15)  NOT NULL,
    [ENDERECO]     VARCHAR (150) NOT NULL,
    [NUMERO]       VARCHAR (10)  NOT NULL,
    [COMPLEMENTO]  VARCHAR (100) NULL,
    [BAIRRO]       VARCHAR (100) NOT NULL,
    [CIDADE]       VARCHAR (150) NOT NULL,
    [UF]           CHAR (2)      NOT NULL,
    [DATA]         DATETIME       NOT NULL,
    [TOKEN] VARCHAR(300) SPARSE NULL, 
    [APIKEY] VARCHAR(50) SPARSE NULL, 
    [ATIVOLOGIN] BIT NOT NULL DEFAULT 0, 
	[CEP]         VARCHAR (8)   NULL,
    CONSTRAINT [PK_FORNECEDOR] PRIMARY KEY CLUSTERED ([FORNECEDORID] ASC)
);
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_FORNECEDOR_CPFCNPJ]
    ON [dbo].FORNECEDOR(CPFCNPJ ASC);





