CREATE TABLE [dbo].[FORNECEDOR_CAPACIDADE_EXTRA]
(
	[CODIGO] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[FORNECEDORID] INT NOT NULL CONSTRAINT FK_CAPACIDADE_EXTRA_fornecedorid FOREIGN KEY ([FORNECEDORID]) REFERENCES FORNECEDOR([FORNECEDORID]),
	[CLIENTEID] INT NOT NULL CONSTRAINT FK_CAPACIDADE_EXTRA_clienteid FOREIGN KEY ([CLIENTEID]) REFERENCES CLIENTES([CLIENTEID]),
	[CAPACIDADE] INT NOT NULL,
	[DATA_INICIAL] DATE NOT NULL,
	[DATA_FINAL] DATE NOT NULL
)
