CREATE TABLE [dbo].[FORNECEDOR_FAIXAS] (
    [CODIGO]       INT            IDENTITY (1, 1) NOT NULL,
    [VALOR]        DECIMAL (5, 5) NOT NULL,
    [FAIXAIN]      INT            NOT NULL,
    [FAIXAOUT]     INT            NOT NULL,
    [FORNECEDORID] INT            NOT NULL,
    [TIPOSMS]      INT            NOT NULL,
    PRIMARY KEY CLUSTERED ([CODIGO] ASC),
    CONSTRAINT [FK_FORNECEDOR_FAIXAS_FORNECEDOR] FOREIGN KEY ([FORNECEDORID]) REFERENCES [dbo].[FORNECEDOR] ([FORNECEDORID]) ON DELETE CASCADE
);

