CREATE TABLE [dbo].[FORNECEDOR_CLIENTE]
(
	[CODIGO] INT NOT NULL PRIMARY KEY IDENTITY, 
    [FORNECEDORID] INT NOT NULL, 
    [CLIENTEID] INT NOT NULL, 
    [ATIVO] BIT NOT NULL, 
    [VISIVEL] BIT NOT NULL, 
    [DATAVINCULO] DATETIME NOT NULL DEFAULT GETDATE(), 
    [DISTRIBUICAO] DECIMAL(18, 2) NULL, 
    [CAPACIDADEENVIO] INT NULL, 
    [ENVIOACADA5MIN] INT NULL, 
    [TIPOSMS] TINYINT NULL, 
    [STATUSFORNECEDOR] TINYINT NOT NULL DEFAULT 3, 
    [USUARIO] VARCHAR(60) NULL, 
    [SENHA] VARCHAR(60) NULL, 
	[TOKEN] VARCHAR(MAX) NULL,
    [STATUSOPERACIONAL] TINYINT NOT NULL DEFAULT 0, 
    CONSTRAINT [FK_FORNECEDOR_CLIENTE_FORNECEDOR] FOREIGN KEY (FORNECEDORID) REFERENCES FORNECEDOR(FORNECEDORID),
	CONSTRAINT [FK_FORNECEDOR_CLIENTE_CLIENTES] FOREIGN KEY (CLIENTEID) REFERENCES CLIENTES(CLIENTEID), 
    CONSTRAINT [CK_FORNECEDOR_CLIENTE_CAPACIDADEENVIO] CHECK (CAPACIDADEENVIO>0),
	CONSTRAINT [CK_FORNECEDOR_CLIENTE_ENVIOACADA5MIN] CHECK (ENVIOACADA5MIN>0)
)
GO
CREATE UNIQUE NONCLUSTERED INDEX IX_CLIENTES_FORNECEDOR ON dbo.FORNECEDOR_CLIENTE
	(
	FORNECEDORID,
	CLIENTEID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)