CREATE TABLE [dbo].[FORNECEDOR_CAPACIDADE] (
    [CODIGO]       INT IDENTITY (1, 1) NOT NULL,
    [FORNECEDORID] INT NOT NULL,
    [OPERADORAID]  INT NOT NULL,
    [CAPACIDADE]   INT NOT NULL,
    [ENVIOS5MIN] INT NULL, 
    PRIMARY KEY CLUSTERED ([CODIGO] ASC),
    CONSTRAINT [FK_FORNECEDOR_CAPACIDADE_FORNECEDOR] FOREIGN KEY ([FORNECEDORID]) REFERENCES [dbo].[FORNECEDOR] ([FORNECEDORID]) ON DELETE CASCADE
);

