CREATE TABLE [dbo].[FORNECEDOR_CONTATO] (
    [CODIGO]       INT IDENTITY (1, 1) NOT NULL,
    [FORNECEDORID] INT NOT NULL,
    [TELEFONE] NUMERIC(14) NULL, 
    [EMAIL] VARCHAR(255) NULL, 
    [DESCRICAO] VARCHAR(150) NULL, 
    PRIMARY KEY CLUSTERED ([CODIGO] ASC),
    CONSTRAINT [FK_FORNECEDOR_CONTATO_FORNECEDOR] FOREIGN KEY ([FORNECEDORID]) REFERENCES [dbo].[FORNECEDOR] ([FORNECEDORID]) ON DELETE CASCADE
);
GO
CREATE NONCLUSTERED INDEX [IX_FORNECEDOR_CONTATO_EMAIL_UNIQUE] ON dbo.FORNECEDOR_CONTATO(EMAIL) WHERE EMAIL IS NOT NULL


