CREATE TABLE [dbo].[GESTOR] (
    [GESTORID]  INT           IDENTITY (1, 1) NOT NULL,
    [NOME]      VARCHAR (150) NOT NULL,
    [CLIENTEID] INT           NOT NULL,
    [DATA]      DATETIME      NOT NULL,
    PRIMARY KEY CLUSTERED ([GESTORID] ASC)
);
GO
CREATE UNIQUE NONCLUSTERED INDEX IX_GESTOR_NOME ON dbo.GESTOR
	(
	NOME,
	CLIENTEID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)