CREATE TABLE [dbo].[GESTOR_CARTEIRAS] (
    [CODIGO]     INT IDENTITY (1, 1) NOT NULL,
    [CARTEIRAID] INT NOT NULL,
    [GESTORID]   INT NOT NULL,
    PRIMARY KEY CLUSTERED ([CODIGO] ASC),
    CONSTRAINT [FK_GESTOR_CARTEIRAS_GESTOR] FOREIGN KEY ([GESTORID]) REFERENCES [dbo].[GESTOR] ([GESTORID]) ON DELETE CASCADE ON UPDATE CASCADE
);
GO
CREATE UNIQUE NONCLUSTERED INDEX IX_GESTOR_CARTEIRAS ON dbo.GESTOR_CARTEIRAS(CARTEIRAID,GESTORID) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)