CREATE TABLE [dbo].[GESTOR_TELEFONES] (
    [CODIGO]   INT          IDENTITY (1, 1) NOT NULL,
    [GESTORID] INT          NOT NULL,
    [TELEFONE] NUMERIC (12) NULL,
    PRIMARY KEY CLUSTERED ([CODIGO] ASC),
    CONSTRAINT [FK_GESTOR_TELEFONES_GESTOR] FOREIGN KEY ([GESTORID]) REFERENCES [dbo].[GESTOR] ([GESTORID]) ON DELETE CASCADE ON UPDATE CASCADE
);
GO

CREATE UNIQUE NONCLUSTERED INDEX IX_GESTOR_TELEFONES ON dbo.GESTOR_TELEFONES(TELEFONE,GESTORID) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
