CREATE TABLE [dbo].[GRUPOUSUARIO_PAGINAS]
(
	[GRUPOUSUARIOPAGINAID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [PAGINAID] INT NOT NULL, 
    [GRUPOUSUARIOID] INT NOT NULL, 
    [PERMISSAO] TINYINT NOT NULL, 
    [SUBPAGINAID] INT NULL, 
    CONSTRAINT [FK_GRUPOUSUARIO_PAGINAS_GRUPOUSUARIO] FOREIGN KEY (GRUPOUSUARIOID) REFERENCES GRUPOUSUARIOS(GRUPOUSUARIOID) ON DELETE CASCADE ON UPDATE CASCADE
)

