CREATE TABLE [dbo].[GRUPOUSUARIOS]
(
	[GRUPOUSUARIOID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [COTA] INT NOT NULL, 
    [SALDO] INT NOT NULL, 
    [CLIENTEID] INT NOT NULL, 
    [SALDOCOMPARTILHADO] BIT NOT NULL, 
    [NOME] VARCHAR(150)  NOT NULL, 
    [ISEXCLUDED] BIT NOT NULL DEFAULT 0, 
    CONSTRAINT [CK_GRUPOUSUARIOS_SALDO] CHECK (SALDO>=0), 
    CONSTRAINT [CK_GRUPOUSUARIOS_COTA] CHECK (COTA>=0),
	CONSTRAINT [CK_GRUPOUSUARIOS_COTA_SALDO] CHECK (COTA>=SALDO)

);
GO
CREATE UNIQUE NONCLUSTERED INDEX IX_GRUPOUSUARIOS_NOME ON dbo.GRUPOUSUARIOS
	(
	NOME,
	CLIENTEID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)