CREATE TABLE [dbo].[IDENTITYSERVER_CLIENTS_SCOPES]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [APISECRET] VARCHAR(50) SPARSE NULL, 
    [USERCLAIMS] VARCHAR(1000) NULL, 
    [API] VARCHAR(50) NOT NULL, 
    [DISPLAYNAME] VARCHAR(150) NOT NULL, 
    [CODIGO] INT NOT NULL,
	[TOKEN] VARCHAR(70) NULL, 
    [DATA] DATETIME NOT NULL , 
    [ISRESETED] BIT NOT NULL DEFAULT 0, 
    CONSTRAINT [FK_IDENTITYSERVER_CLIENTS_SCOPES_IDENTITYSERVER_CLIENTS] FOREIGN KEY (CODIGO) REFERENCES IDENTITYSERVER_CLIENTS(CODIGO)
)
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_IDENTITYSERVER_CLIENTS_SCOPES_TOKEN] ON [dbo].[IDENTITYSERVER_CLIENTS_SCOPES] (TOKEN,API)
GO
CREATE NONCLUSTERED INDEX [IX_IDENTITYSERVER_CLIENTS_SCOPES_TOKEN_Includes] ON dbo.IDENTITYSERVER_CLIENTS_SCOPES (TOKEN) INCLUDE(APISECRET,API)