CREATE TABLE [dbo].[LAYOUT]
(
	[LEIAUTEID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [NOME] VARCHAR(250) NOT NULL, 
    [CLIENTEID] INT NULL, 
    [USUARIOID] INT NULL, 
    [DATA] DATETIME NOT NULL, 
    [VISIVEL] BIT NOT NULL DEFAULT 1, 
    [PADRAO] BIT NOT NULL,
	[ISESPECIAL] BIT NOT NULL DEFAULT 0
)
GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_LAYOUT_UNIQUE_CLIENTEID_NOME] ON [dbo].[LAYOUT] (CLIENTEID ASC, NOME ASC)
