CREATE TABLE [dbo].[LAYOUT_VARIAVEIS]
(
	[CODIGO] INT NOT NULL PRIMARY KEY IDENTITY, 
    [LEIAUTEID] INT NOT NULL, 
    [VARIAVEL] VARCHAR(150) NOT NULL, 
    [IDCOLUNA] SMALLINT NOT NULL,
	[INICIO] SMALLINT NULL,
	[TAMANHO] SMALLINT NULL,
    CONSTRAINT [FK_LAYOUT_VARIAVEIS_LAYOUT_VARIAVEIS] FOREIGN KEY ([LEIAUTEID]) REFERENCES LAYOUT([LEIAUTEID]) ON DELETE CASCADE
)
GO
CREATE UNIQUE NONCLUSTERED INDEX IX_VARIAVEL_LAYOUT ON dbo.LAYOUT_VARIAVEIS ([LEIAUTEID] ASC, VARIAVEL ASC)
GO
CREATE UNIQUE NONCLUSTERED INDEX IX_IDCOLUNA_LAYOUT ON dbo.LAYOUT_VARIAVEIS(LEIAUTEID ASC, IDCOLUNA ASC)
