CREATE TABLE [dbo].[LOG_ATIVIDADE]
(
	[CODIGO] INT NOT NULL PRIMARY KEY IDENTITY, 
    [CLIENTEID] INT NOT NULL, 
    [USUARIOID] INT NULL, 
    [DATA] DATETIME NOT NULL, 
    [DESCRICAO] VARCHAR(250) NOT NULL, 
    [TIPOATIVIDADE] TINYINT NOT NULL, 
    [DATADIA] DATE NOT NULL,
	[MODULO] TINYINT NOT NULL,
	[CARTEIRAID] INT NULL,
	CONSTRAINT [FK_LOG_ATIVIDADE_CARTEIRAID] FOREIGN KEY ([CARTEIRAID]) REFERENCES [dbo].[CARTEIRAS] ([CARTEIRAID])
)
