CREATE TABLE [dbo].[MOTIVO_BLACKLIST] (
    [CODIGO]    INT           IDENTITY (1, 1) NOT NULL,
    [MOTIVO]    VARCHAR (150) NOT NULL,
    [CLIENTEID] INT           NOT NULL,
    PRIMARY KEY CLUSTERED ([CODIGO] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_MOTIVO_BLACKLIST]
    ON [dbo].[MOTIVO_BLACKLIST]([CLIENTEID] ASC, [MOTIVO] ASC);

