CREATE TABLE [dbo].[OPERADORA] (
    [OPERADORAID] INT          IDENTITY (1, 1) NOT NULL,
    [OPERADORA]   VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_OPERADORA] PRIMARY KEY CLUSTERED ([OPERADORAID] ASC)
);

