CREATE TABLE [dbo].[PADRAO_POSTAGENS]
(
	[CODIGO] INT NOT NULL PRIMARY KEY IDENTITY, 
    [PADRAO] VARCHAR(255) NOT NULL, 
    [CARTEIRAID] INT NOT NULL, 
    [CLIENTEID] INT NOT NULL, 
    [TIPOCAMPANHAID] INT NOT NULL, 
    [USUARIOID] INT NULL, 
    [LEIAUTEID] INT NOT NULL, 
    CONSTRAINT [FK_PADRAO_POSTAGENS_CARTEIRAS] FOREIGN KEY (CARTEIRAID) REFERENCES CARTEIRAS(CARTEIRAID) ON DELETE CASCADE, 
    CONSTRAINT [FK_PADRAO_POSTAGENS_TIPOCAMPANHA] FOREIGN KEY (TIPOCAMPANHAID) REFERENCES dbo.TIPOCAMPANHA(CODIGO) ON DELETE CASCADE,
	CONSTRAINT [FK_PADRAO_POSTAGENS_LAYOUTID] FOREIGN KEY ([LEIAUTEID]) REFERENCES dbo.LAYOUT ([LEIAUTEID]) ON DELETE CASCADE
);
GO
CREATE UNIQUE NONCLUSTERED INDEX IX_PADRAO_POSTAGENS ON dbo.[PADRAO_POSTAGENS]([PADRAO],CLIENTEID) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

