CREATE TABLE [dbo].[PORTABILIDADE] (
    [CODIGO]      INT          IDENTITY (1, 1) NOT NULL,
    [NUMERO]      NUMERIC (11) NOT NULL,
    [OPERADORAID] INT          NOT NULL,
    PRIMARY KEY CLUSTERED ([CODIGO] ASC)
);


GO

CREATE NONCLUSTERED INDEX [IX_PORTABILIDADE_NUMERO]
ON [dbo].[PORTABILIDADE] ([NUMERO])