CREATE TABLE [dbo].[PREFIXOS] (
    [CODIGO]      INT IDENTITY (1, 1) NOT NULL,
    [PREFIXO]     INT NOT NULL,
    [OPERADORAID] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([CODIGO] ASC)
);
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PREFIXOS]
    ON [dbo].[PREFIXOS]([PREFIXO] ASC);

