CREATE TABLE [dbo].[RATINHOS]
(
	[CODIGO] INT NOT NULL PRIMARY KEY IDENTITY, 
    [CELULAR] NUMERIC(12) NOT NULL, 
    [DATA] DATETIME NOT NULL
)

GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_RATINHOS_CELULAR] ON [dbo].[RATINHOS] (CELULAR)
