CREATE TABLE [dbo].[RATINHOS_RECEBIMENTO]
(
	[CODIGO] INT NOT NULL PRIMARY KEY IDENTITY, 
    [CELULAR] NUMERIC(12) NOT NULL, 
    [DATADIA] DATE NOT NULL, 
    [TEXTO] VARCHAR(320) NOT NULL, 
    [CLIENTEID] INT NOT NULL, 
    [FORNECEDORID] INT NOT NULL, 
    [DATARECEBIMENTO] DATETIME NULL
)
GO
CREATE NONCLUSTERED INDEX IX_RATINHOS_RECEDBIMENTO ON dbo.RATINHOS_RECEBIMENTO (CELULAR, [DATADIA], TEXTO)
GO
CREATE UNIQUE NONCLUSTERED INDEX IX_RATTINHOS_RECEBIMENTO_UNIQUE ON dbo.RATINHOS_RECEBIMENTO (CELULAR ASC, [DATADIA] ASC, [TEXTO])