CREATE TABLE [dbo].[REJEITADAS_ANTERIORES]
(
	[CODIGO] INT NOT NULL PRIMARY KEY IDENTITY, 
    [CELULAR] NUMERIC(11) NOT NULL, 
    [DATA] DATE NOT NULL
)
GO

CREATE NONCLUSTERED INDEX [IX_REJEITADAS_ANTERIORES_CELULAR_Includes] ON [dbo].[REJEITADAS_ANTERIORES] ([DATA]) INCLUDE ([CELULAR])
