CREATE TABLE [dbo].[REQUISICAO_RELATORIO]
(
	[REQUISICAOID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [CLIENTEID] INT NOT NULL, 
    [USUARIOID] INT NULL, 
    [DATA] DATETIME NOT NULL, 
    [DATAINICIAL] DATE NOT NULL, 
    [DATAFINAL] DATE NOT NULL, 
    [TIPORELATORIO] TINYINT NOT NULL, 
    [ARQUIVO] VARCHAR(250) NOT NULL, 
    [STATUSRELATORIO] TINYINT NOT NULL, 
    [TAMANHO] DECIMAL(8, 2) NULL 
)
