CREATE TABLE [dbo].[REQUISICAO_RELATORIO_EMAILS]
(
	[CODIGO] INT NOT NULL PRIMARY KEY IDENTITY, 
    [EMAIL] VARCHAR(250) NOT NULL, 
    [REQUISICAOID] INT NOT NULL, 
    CONSTRAINT [FK_REQUISICAO_RELATORIO_EMAILS_REQUISICAO_RELATORIO] FOREIGN KEY (REQUISICAOID) REFERENCES REQUISICAO_RELATORIO(REQUISICAOID) ON DELETE CASCADE
	 
)
