CREATE TABLE [dbo].[RETORNO_CONSOLIDADO]
(
	[CODIGO] INT NOT NULL PRIMARY KEY IDENTITY, 
    [FORNECEDORID] INT NOT NULL CONSTRAINT FK_USUARIO_FORNECEDORID FOREIGN KEY ([FORNECEDORID]) REFERENCES FORNECEDOR([FORNECEDORID]),
    [CLASSIFICACAOID] INT NOT NULL CONSTRAINT FK_USUARIO_CLASSIFICACAOID FOREIGN KEY ([CLASSIFICACAOID]) REFERENCES RETORNO_CLASSIFICACAO([CODIGO]),
    [QUANTIDADE] INT NOT NULL,
	[CLIENTEID] INT NOT NULL CONSTRAINT FK_USUARIO_CLIENTEID FOREIGN KEY ([CLIENTEID]) REFERENCES CLIENTES([CLIENTEID]), 
    [DATADIA] DATE NOT NULL,	
    [CARTEIRAID] INT NOT NULL CONSTRAINT FK_USUARIO_CARTEIRAID FOREIGN KEY ([CARTEIRAID]) REFERENCES CARTEIRAS([CARTEIRAID]), 
    [ARQUIVOID] INT NULL CONSTRAINT FK_USUARIO_ARQUIVOID FOREIGN KEY ([ARQUIVOID]) REFERENCES CAMPANHAS_ARQUIVOS([ARQUIVOID]), 
    [USUARIOID] INT NULL CONSTRAINT FK_USUARIO_USUARIOID FOREIGN KEY ([USUARIOID]) REFERENCES USUARIOS(USUARIOID),
    [HORA] TINYINT NOT NULL
)