CREATE TABLE [dbo].[SESSION_ITENS]
(
	[CODIGO] INT NOT NULL PRIMARY KEY IDENTITY, 
    [GUID] VARCHAR(60) NOT NULL, 
    [KEY] VARCHAR(150) NOT NULL, 
    [VALUE] VARBINARY(MAX) NOT NULL, 
    [DATA] DATETIME NOT NULL
)

GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_SESSION_ITENS_KEY_GUID] ON [dbo].[SESSION_ITENS] ([KEY] ASC, [GUID] ASC)
