CREATE TABLE [dbo].[SUBPAGINAS]
(
	[SUBPAGINAID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [SUBPAGINA] VARCHAR(150) NOT NULL, 
    [PAGINAID] INT NOT NULL, 
    CONSTRAINT [FK_SUBPAGINAS_PAGINAS] FOREIGN KEY (PAGINAID) REFERENCES dbo.PAGINAS(PAGINAID)
)
