CREATE TABLE [dbo].[TIPOCAMPANHA] (
    [CODIGO]       INT           IDENTITY (1, 1) NOT NULL,
    [TIPOCAMPANHA] VARCHAR (150) NOT NULL,
    [CLIENTEID]    INT           NOT NULL,
    [VISIVEL] BIT NOT NULL, 
    [ISEXCLUDED] BIT NOT NULL DEFAULT 0, 
    CONSTRAINT [PK__TIPOCAMP__CC87E1272DC8280D] PRIMARY KEY CLUSTERED ([CODIGO] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_TIPOCAMPANHA]
    ON [dbo].[TIPOCAMPANHA]([CLIENTEID] ASC, [TIPOCAMPANHA] ASC, ISEXCLUDED ASC);

