CREATE TABLE [dbo].[USERS_RESETPASSWORD]
(
	[CODIGO] INT NOT NULL PRIMARY KEY IDENTITY, 
    [CLIENTEID] INT NOT NULL, 
    [USUARIOID] INT NULL, 
    [DATA] DATETIME NOT NULL, 
    [TOKEN] VARCHAR(36) NOT NULL, 
    [SENHATROCADA] BIT NOT NULL, 
    CONSTRAINT [FK_USERS_RESETPASSWORD_USERS] FOREIGN KEY (USUARIOID) REFERENCES dbo.USUARIOS(USUARIOID) ON DELETE CASCADE, 
	CONSTRAINT [FK_USERS_RESETPASSWORD_CLIENTES] FOREIGN KEY (CLIENTEID) REFERENCES dbo.CLIENTES(CLIENTEID) ON DELETE CASCADE, 
)
GO
CREATE  NONCLUSTERED INDEX [IX_USERS_RESETPASSWORD_TOKENUNIQUE] ON dbo.USERS_RESETPASSWORD(TOKEN)