CREATE TABLE [dbo].[USUARIOS] (
    [USUARIOID]      INT           NOT NULL IDENTITY,
    [NOME]           VARCHAR (100) NOT NULL,
    [LOGINUSER]      VARCHAR (25)  NOT NULL,
    [CLIENTEID]      INT           NOT NULL,
    [SALDO]          INT           NOT NULL,
    [SALDOILIMITADO] BIT           NOT NULL,
    [EMAIL]          VARCHAR (150) NOT NULL,
    [TELEFONE]       NUMERIC (11)  NULL,
    [DATA]           DATETIME      NOT NULL,
    [ATIVO]          BIT           NOT NULL,
    [GRUPOUSUARIOID] INT NOT NULL, 
    [COTA] INT NULL, 
    [ADMPERFIL] BIT NOT NULL DEFAULT 0, 
    [SENHATROCADA] BIT NOT NULL DEFAULT 0, 
    [ISEXCLUDED] BIT NOT NULL DEFAULT 0, 
    PRIMARY KEY CLUSTERED ([USUARIOID] ASC), 
	CONSTRAINT [CK_USUARIOS_SALDO] CHECK (SALDO>=0), 
    CONSTRAINT [FK_USUARIOS_GRUPOUSUARIOS] FOREIGN KEY (GRUPOUSUARIOID) REFERENCES dbo.[GRUPOUSUARIOS]([GRUPOUSUARIOID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_USUARIOS_EMAIL]
    ON [dbo].[USUARIOS]([EMAIL],ISEXCLUDED);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_USUARIOS_LOGINUSER]
    ON [dbo].[USUARIOS]([LOGINUSER] ASC, ISEXCLUDED);

