CREATE TABLE [dbo].[USUARIOS_CARTEIRA] (
    [CODIGO]     INT IDENTITY (1, 1) NOT NULL,
    [USUARIOID]  INT NOT NULL,
    [CARTEIRAID] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([CODIGO] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_USUARIOS_CARTEIRA]
    ON [dbo].[USUARIOS_CARTEIRA]([CARTEIRAID] ASC, [USUARIOID] ASC);

