CREATE PROC dbo.CAMPANHA_RETORNO_PAGINACAO --'2017-4-25', '2017-4-28', 1, null
@DataInicial	DATETIME,
@DataFinal		DATETIME,
@ClienteID		INT,
@Search			VARCHAR(150),
@PageSize		INT,
@PageNumber		INT,
@CarteiraID		INT,
@UsuarioID		INT
AS
BEGIN
CREATE TABLE #TMP(
FORNECEDORID	INT,
TEXTO			VARCHAR(160),
IDCLIENTE		VARCHAR(50),
CELULAR			NUMERIC(12,0),
RETORNOCLIENTE	VARCHAR(320),
ARQUIVO			VARCHAR(255),
CODIGO			INT,
DATARETORNO		DATETIME,
CARTEIRA		VARCHAR(150), 
REGISTROS		INT,
USUARIOID		INT
);
			WITH RETORNOS AS
			(
			SELECT CR.FORNECEDORID, C.TEXTO, C.IDCLIENTE, C.CELULAR, CR.RETORNO, CA.ARQUIVO, CODIGO, DATARETORNO,CAT.CARTEIRA,  ROW_NUMBER() OVER ( ORDER BY CODIGO ) REGISTRO, C.USUARIOID FROM CAMPANHA_RETORNO CR 
												LEFT JOIN CAMPANHAS C  ON CR.CAMPANHAID=C.CAMPANHAID
												LEFT JOIN CAMPANHAS_ARQUIVOS CA  ON C.ARQUIVOID=CA.ARQUIVOID
												LEFT JOIN CARTEIRAS CAT ON  C.CARTEIRAID=CAT.CARTEIRAID
												WHERE CR.DATARETORNO BETWEEN @DataInicial AND @DataFinal AND C.CLIENTEID=@ClienteID 
												GROUP BY CR.FORNECEDORID, C.TEXTO, C.IDCLIENTE, C.CELULAR, CR.RETORNO, CA.ARQUIVO, C.CAMPANHAID, CODIGO, DATARETORNO, CAT.CARTEIRA, C.USUARIOID
			)
			INSERT INTO #TMP
			SELECT FORNECEDORID, TEXTO, IDCLIENTE, CELULAR, RETORNO, ARQUIVO, CODIGO, DATARETORNO, CARTEIRA, REGISTRO, USUARIOID FROM RETORNOS

			SELECT CLASSIFICACAO, COUNT(CLASSIFICACAO) QUANTIDADE FROM #TMP GROUP BY CLASSIFICACAO
			SELECT FORNECEDORID, TEXTO, IDCLIENTE, CELULAR, RETORNO, ARQUIVO, CODIGO, DATARETORNO, CARTEIRA, REGISTRO, USUARIOID FROM #TMP WHERE CARTEIRAID=@CarteiraID ORDER BY DATARETORNO OFFSET @PageSize * (@PageNumber - 1) ROWS FETCH NEXT @PageSize ROWS ONLY;
			END