CREATE PROC [dbo].[CONSOLIDADO_CAMPANHAS_AGENDADA] --'2017-8-25','2017-8-25'  
@DataInicial DATE,      
@DataFinal  DATE      
AS      
BEGIN  TRANSACTION  
BEGIN TRY  
  
CREATE TABLE #TMP(      
  
QUANTIDADE  INT,      
ARQUIVOID  INT,       
FORNECEDORID INT,      
CARTEIRAID  INT,       
DATAENVIAR  SMALLDATETIME,       
DATADIA   DATE,      
STATUSENVIO  TINYINT,      
STATUSREPORT TINYINT,      
CLIENTEID  INT,      
USUARIOID  INT,      
SPCAPITAL  INT,      
SPGRANDE  INT,      
DEMAISDDD  INT,  
TIPOCAMPANHAID INT,  
ATRASO INT  
);      
  
  WITH ENVIADAS AS      
  (      
   SELECT CAMPANHAID, ARQUIVOID, CARTEIRAID, STATUSREPORT, STATUSENVIO, FORNECEDORID, DATAENVIAR, DATADIA, CLIENTEID, USUARIOID,  
   IIF(CAST(SUBSTRING(CAST(CELULAR AS VARCHAR(11)), 0, 3) AS TINYINT)=11, 1, 0) SPCAPITAL,  
   IIF(CAST(SUBSTRING(CAST(CELULAR AS VARCHAR(11)), 0, 3) AS TINYINT)>11 AND CAST(SUBSTRING(CAST(CELULAR AS VARCHAR(11)), 0, 3) AS TINYINT)<=19, 1, 0) SPGRANDE,  
   IIF(CAST(SUBSTRING(CAST(CELULAR AS VARCHAR(11)), 0, 3) AS TINYINT)>19, 1, 0) DEMAISDDD, TIPOCAMPANHAID, DATEDIFF(SECOND, DATAENVIAR, ISNULL([DATAENVIOFORNECEDOR], DATAENVIAR)) DIFERENCA  
   FROM CAMPANHAS WHERE DATADIA BETWEEN @DataInicial AND @DataFinal      
  )      
  
  INSERT #TMP      
  SELECT COUNT(CAMPANHAID), ARQUIVOID, FORNECEDORID, CARTEIRAID, DATAENVIAR, DATADIA,       
  CASE WHEN STATUSENVIO=1 OR STATUSENVIO=0 THEN 3 ELSE STATUSENVIO END, STATUSREPORT, CLIENTEID, USUARIOID      
  ,SUM(SPCAPITAL) SPCAPITAL, SUM(SPGRANDE) SPGRANDE, SUM(DEMAISDDD) DEMAISDDD, TIPOCAMPANHAID, AVG(CAST(DIFERENCA AS BIGINT))  
  FROM ENVIADAS GROUP BY ARQUIVOID, FORNECEDORID, CARTEIRAID, DATAENVIAR, DATADIA, STATUSENVIO, FORNECEDORID, STATUSREPORT, CLIENTEID, USUARIOID, TIPOCAMPANHAID   
  
  DECLARE @TMP TABLE (      
  CODIGO   INT IDENTITY(1,1),      
  CARTEIRAID  INT,       
  ARQUIVOID  INT,       
  DATAENVIAR  SMALLDATETIME,       
  DATADIA   DATE,      
  FORNECEDORID INT,      
  STATUSREPORT TINYINT,      
  ERRO   INT,      
  SUSPENSA  INT,      
  CANCELADA  INT,      
  CLIENTEID  INT,      
  USUARIOID  INT,      
  ENVIADA   INT,      
  SPCAPITAL  INT,      
  SPGRANDE  INT,      
  DEMAISDDD  INT,  
  TIPOCAMPANHAID INT,  
  ATRASO INT  
  );      
   
  INSERT @TMP      
  SELECT CARTEIRAID, ARQUIVOID, DATAENVIAR, DATADIA, FORNECEDORID, ISNULL(STATUSREPORT, 99) STATUSREPORT,ISNULL([3],0) ERRO, ISNULL([4],0) SUSPENSA, ISNULL([5],0) CANCELADA, CLIENTEID, USUARIOID, ISNULL([2],0) ENVIADA, SPCAPITAL, SPGRANDE, DEMAISDDD, TIPOCAMPANHAID, ATRASO FROM     
  (SELECT QUANTIDADE, STATUSENVIO, CARTEIRAID, ARQUIVOID, DATAENVIAR, DATADIA, FORNECEDORID, STATUSREPORT, CLIENTEID, USUARIOID, SPCAPITAL, SPGRANDE, DEMAISDDD, TIPOCAMPANHAID, ATRASO FROM #TMP) AS PVT PIVOT(SUM(QUANTIDADE) FOR STATUSENVIO IN([2],[3],[4],[5])) AS P;      
  
  WITH CONSOLIDADA AS(      
  SELECT SUSPENSA, CANCELADA, ERRO, ARQUIVOID, CARTEIRAID, DATAENVIAR, FORNECEDORID, DATADIA, ISNULL([68],0) EXCLUIDA, ISNULL([0], 0) ENTREGUE, ISNULL([70],0) EXPIRADA, CLIENTEID, USUARIOID, ISNULL([99],0) ENVIADA, SPCAPITAL, SPGRANDE, DEMAISDDD, TIPOCAMPANHAID, ATRASO FROM       
  (SELECT SUSPENSA, ERRO, CANCELADA, ARQUIVOID, DATAENVIAR, FORNECEDORID, STATUSREPORT, CARTEIRAID, DATADIA, CLIENTEID, USUARIOID, ENVIADA, SPCAPITAL, SPGRANDE, DEMAISDDD, TIPOCAMPANHAID, ATRASO FROM @TMP) AS PVT PIVOT (SUM(ENVIADA) FOR STATUSREPORT IN([68],[0],[70], [99])) AS P)   
  
  INSERT CAMPANHAS_CONSOLIDADO      
  SELECT CARTEIRAID, ARQUIVOID,  DATAENVIAR, USUARIOID, CLIENTEID,EXCLUIDA,ERRO,SUSPENSA,ENTREGUE,EXPIRADA, DATADIA, FORNECEDORID, CANCELADA, SPCAPITAL, SPGRANDE, DEMAISDDD, ENVIADA, TIPOCAMPANHAID, ATRASO FROM CONSOLIDADA C      
  
  DROP TABLE #TMP    
  
  INSERT INTO CELULARES_INVALIDOS_CONSOLIDADO    
  SELECT TIPOINVALIDO, CLIENTEID, USUARIOID, COUNT(CODIGO), CARTEIRAID, ARQUIVO, CAST(DATAENVIAR AS DATE) FROM  [dbo].[CELULARES_INVALIDOS] WHERE  DATAENVIAR BETWEEN @DataInicial AND DATEADD(MINUTE, 1439,CAST(@DataFinal AS SMALLDATETIME)) GROUP BY CLIENTEID, USUARIOID, CARTEIRAID, ARQUIVO, CAST(DATAENVIAR AS DATE), TIPOINVALIDO    
  
  INSERT INTO RETORNO_CONSOLIDADO  
  --SELECT FORNECEDORID, [0] POSITIVO ,[1] NEGATIVO, [2] NEUTRO, CLIENTEID, DATADIA, CARTEIRAID, ARQUIVOID, USUARIOID, DATARETORNO FROM  
  --  (SELECT CE.FORNECEDORID, [CLASSIFICACAO],CODIGO, DATEPART(hh, DATARETORNO) DATARETORNO, C.CLIENTEID, C.USUARIOID, CAST(DATARETORNO AS DATE) DATADIA, C.CARTEIRAID, C.ARQUIVOID FROM CAMPANHA_RETORNO CE JOIN CAMPANHAS C ON CE.CAMPANHAID=C.CAMPANHAID WHERE C.DATADIA='2017-8-24')   
  --  AS PVT PIVOT (COUNT(CODIGO) FOR [CLASSIFICACAO] IN([0],[1],[2])) AS P
	SELECT CR.FORNECEDORID, CR.CLASSIFICACAOID, COUNT(CODIGO), C.CLIENTEID, CAST(DATARETORNO AS DATE) DATARETORNO,C.CARTEIRAID, C.ARQUIVOID, C.USUARIOID, DATEPART(hh, DATARETORNO) HORARETORNO
	FROM CAMPANHA_RETORNO CR JOIN CAMPANHAS C ON CR.CAMPANHAID=C.CAMPANHAID WHERE CR.DATARETORNO BETWEEN @DataInicial AND DATEADD(SECOND, 86399,CAST(@DataFinal AS datetime)) GROUP BY  
	CR.FORNECEDORID, CR.CLASSIFICACAOID, C.CLIENTEID, CAST(DATARETORNO AS DATE),C.CARTEIRAID, C.ARQUIVOID, C.USUARIOID, DATEPART(hh, DATARETORNO)
  
  
  
    COMMIT TRANSACTION  
    END TRY  
    BEGIN CATCH  
    SELECT @@ERROR  
    ROLLBACK TRANSACTION  
    END CATCH  
  


  