CREATE PROC dbo.CONSOLIDADO_STATUS_PAGINACAO --10, 1,'2017-4-26', '2017-4-30', 1, NULL, 0,0,NULL, 1,1
@PaginaSize		INT,
@PaginaAtual	INT,
@DataInicial	DATE,
@DataFinal		DATE,
@ClienteID		INT,
@UsuarioID		INT,
@Paginas		INT OUTPUT,
@Registros		INT OUTPUT,
@Search			VARCHAR(150),
@StatusEnvio	TINYINT,
@CarteiraID		INT
AS
BEGIN
DECLARE @TMP TABLE (
ARQUIVO			VARCHAR(255),
ARQUIVOID		INT,
CARTEIRA		VARCHAR(150), 
CARTEIRAID		INT,
DATAENVIAR		SMALLDATETIME,
QUANTIDADE		INT,
REGISTROS		INT,
USUARIOID		INT
);
IF @Search IS NULL
BEGIN
	WITH CONSOLIDADA AS
	(
		SELECT C.CARTEIRAID, C.ARQUIVOID, DATAENVIAR, C.USUARIOID, CAMPANHAID, CAT.CARTEIRA FROM CAMPANHAS C
												JOIN CARTEIRAS CAT ON C.CARTEIRAID=CAT.CARTEIRAID
		WHERE C.CLIENTEID=@ClienteID AND DATADIA BETWEEN @DataInicial AND @DataFinal AND STATUSENVIO=@StatusEnvio
	)
	INSERT @TMP
	SELECT  ARQUIVO, C.ARQUIVOID, CARTEIRA, CARTEIRAID, DATAENVIAR, COUNT(CAMPANHAID) QUANTIDADE, ROW_NUMBER() OVER ( ORDER BY DATAENVIAR ) REGISTRO, C.USUARIOID 
	FROM CONSOLIDADA C
	LEFT JOIN CAMPANHAS_ARQUIVOS CA ON C.ARQUIVOID=CA.ARQUIVOID
	GROUP BY ARQUIVO, C.ARQUIVOID, CARTEIRA, CARTEIRAID, DATAENVIAR, C.USUARIOID ORDER BY DATAENVIAR
END
ELSE
BEGIN	
WITH CONSOLIDADA AS
	(
				SELECT C.CARTEIRAID, C.ARQUIVOID, DATAENVIAR, C.USUARIOID, CAMPANHAID, CAT.CARTEIRA FROM CAMPANHAS C
										JOIN CARTEIRAS CAT ON C.CARTEIRAID=CAT.CARTEIRAID
										WHERE C.CLIENTEID=@ClienteID AND DATADIA BETWEEN @DataInicial AND @DataFinal AND STATUSENVIO=@StatusEnvio
	)
	INSERT @TMP
	SELECT  ARQUIVO, C.ARQUIVOID, CARTEIRA, CARTEIRAID, DATAENVIAR, COUNT(CAMPANHAID) QUANTIDADE, ROW_NUMBER() OVER ( ORDER BY DATAENVIAR ) REGISTRO, C.USUARIOID 
	FROM CONSOLIDADA C 
	LEFT JOIN CAMPANHAS_ARQUIVOS CA ON C.ARQUIVOID=CA.ARQUIVOID
	WHERE CARTEIRA LIKE '%'+@Search+'%' OR ARQUIVO LIKE '%'+@Search+'%'
	GROUP BY ARQUIVO, C.ARQUIVOID, CARTEIRA, CARTEIRAID, DATAENVIAR, C.USUARIOID ORDER BY DATAENVIAR
END
	DECLARE @TOTALREGISTROS INT=(SELECT COUNT(ARQUIVO) FROM @TMP)
	SET @PAGINAS=@TOTALREGISTROS/@PAGINASIZE
	SET @Registros=@TOTALREGISTROS

	IF(@UsuarioID IS NULL)
		SELECT ARQUIVO, ARQUIVOID, CARTEIRA, CARTEIRAID, DATAENVIAR, QUANTIDADE, USUARIOID FROM @TMP T
		WHERE T.REGISTROS BETWEEN (@PAGINAATUAL-1)*@PAGINASIZE AND ((@PAGINAATUAL-1)*@PAGINASIZE)+@PAGINASIZE
	ELSE
		SELECT ARQUIVO, ARQUIVOID, CARTEIRA, CARTEIRAID, DATAENVIAR, QUANTIDADE, USUARIOID FROM @TMP T
		WHERE T.REGISTROS BETWEEN (@PAGINAATUAL-1)*@PAGINASIZE AND ((@PAGINAATUAL-1)*@PAGINASIZE)+@PAGINASIZE AND USUARIOID=@UsuarioID

END