CREATE PROC [dbo].[ATUALIZAGRUPOUSUARIOS]
@ClienteID			INT,
@GrupoUsuarioID		INT,
@Saldo				FLOAT,
@Cota				FLOAT,
@Nome				VARCHAR(150),
@SaldoCompartilhado BIT
AS
BEGIN
DECLARE @CotaOriginal FLOAT=(SELECT CAST(COTA AS FLOAT) FROM GRUPOUSUARIOS WHERE GRUPOUSUARIOID=@GrupoUsuarioID);

IF (@Cota < @CotaOriginal)
BEGIN

	DECLARE @ReducaoCota FLOAT= 100-(@Cota/@CotaOriginal*100);
	
	UPDATE U SET 
			COTA=CAST(CAST(U.COTA AS FLOAT)-(CAST(U.COTA AS FLOAT)*@ReducaoCota/100) AS INT),
			SALDO = CAST(CAST(U.SALDO AS FLOAT)-(CAST(U.SALDO AS FLOAT)*@ReducaoCota/100) AS INT)
			FROM USUARIOS U WHERE GRUPOUSUARIOID=@GrupoUsuarioID
END
UPDATE GRUPOUSUARIOS SET NOME=@Nome, COTA=@Cota, SALDO=@Saldo, SALDOCOMPARTILHADO=@SaldoCompartilhado WHERE CLIENTEID=@ClienteID AND GRUPOUSUARIOID=@GrupoUsuarioID
END
GO


